server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE

employees:
  backend-url: http://localhost:8081
spring:
  application:
    name: employees-frontend
  cloud:
    stream:
      bindings:
        createEmployee:
          destination: employee-backend-command
          content-type: application/*+avro
        employeeCreated-in-0:
          destination: employee-backend-event
          content-type: application/*+avro
      kafka:
        binder:
          enable-observation: true
